import React, { useEffect } from 'react';

const LoginForm = () => {
  // Generate background blocks
  useEffect(() => {
    const background = document.querySelector('.background');
    const blockCount = 256; // 16x16 grid

    for (let i = 0; i < blockCount; i++) {
      const block = document.createElement('div');
      block.classList.add('block');
      background.appendChild(block);
    }
  }, []);

  return (
    <div className="flex justify-center items-center min-h-screen bg-[#23242a] overflow-hidden">
      {/* Background blocks */}
      <div className="background fixed top-0 left-0 w-full h-full flex flex-wrap gap-[2px] z-0">
        {/* Blocks will be generated by JavaScript */}
      </div>

      {/* Login form */}
      <div className="signin relative w-[380px] h-[420px] bg-[#1c1c1c] rounded-lg overflow-hidden z-10">
        {/* Animated border */}
        <div className="absolute top-[-50%] left-[-50%] w-[380px] h-[420px] bg-gradient-to-b from-transparent via-[#45f3ff] to-[#45f3ff] origin-bottom-right animate-spin-slow"></div>
        <div className="absolute top-[-50%] left-[-50%] w-[380px] h-[420px] bg-gradient-to-b from-transparent via-[#45f3ff] to-[#45f3ff] origin-bottom-right animate-spin-slow animation-delay-[-3s]"></div>

        {/* Form content */}
        <div className="content absolute inset-[2px] bg-[#28292d] rounded-lg z-20 p-[50px_40px] flex flex-col">
          <h2 className="text-[#45f3ff] font-medium text-center tracking-wider mb-[35px]">Sign In</h2>
          <div className="form">
            {/* Username input */}
            <div className="inputBox relative w-full mt-[35px]">
              <input
                type="text"
                required
                className="relative w-full pt-[20px] pb-[10px] px-[10px] bg-transparent border-none outline-none text-white text-base tracking-wider z-10"
              />
              <i className="absolute left-0 pt-[20px] pb-[10px] px-0 text-[#8f8f8f] pointer-events-none tracking-wider transition-all duration-500">Username</i>
            </div>

            {/* Password input */}
            <div className="inputBox relative w-full mt-[35px]">
              <input
                type="password"
                required
                className="relative w-full pt-[20px] pb-[10px] px-[10px] bg-transparent border-none outline-none text-white text-base tracking-wider z-10"
              />
              <i className="absolute left-0 pt-[20px] pb-[10px] px-0 text-[#8f8f8f] pointer-events-none tracking-wider transition-all duration-500">Password</i>
            </div>

            {/* Links */}
            <div className="links flex justify-between mt-[20px] mb-[20px]">
              <a href="#" className="text-[#8f8f8f] text-sm no-underline hover:text-[#45f3ff]">Forgot Password</a>
              <a href="#" className="text-[#8f8f8f] text-sm no-underline hover:text-[#45f3ff]">Signup</a>
            </div>

            {/* Submit button */}
            <div className="inputBox">
              <input
                type="submit"
                value="Login"
                className="w-full bg-[#45f3ff] text-[#1c1c1c] py-[10px] rounded-md font-semibold cursor-pointer"
              />
            </div>
          </div>
        </div>
      </div>

      {/* Add custom styles for the background blocks */}
      <style>
        {`
          .block {
            position: relative;
            display: block;
            width: calc(6.25vw - 2px);
            height: calc(6.25vw - 2px);
            background: #1a4749;
            opacity: 0.15;
            transition: 1s;
            pointer-events: auto;
          }

          .block:hover {
            background: #45f3ff;
            opacity: 0.2;
            transition: 0s;
          }
        `}
      </style>
    </div>
  );
};

export default LoginForm;